version: '3.8'

services:
  # 1. Database Service
  mysqldb:  # <-- TÃªn nÃ y Ä‘Æ°á»£c dÃ¹ng lÃ m host trong chuá»—i káº¿t ná»‘i
    image: mysql:8.0
    restart: always
    environment:
      # Láº¥y giÃ¡ trá»‹ tá»« file .env Ä‘á»ƒ táº¡o DB láº§n Ä‘áº§u
      MYSQL_DATABASE: ${MYSQL_DB_NAME}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network
    command: --default-authentication-plugin=mysql_native_password

  # 2. Elasticsearch Service
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.10
    environment:
      - discovery.type=single-node
      # Giá»›i háº¡n RAM Ä‘á»ƒ trÃ¡nh sáº­p server (quan trá»ng cho cáº£ mÃ¡y local vÃ  AWS)
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
    volumes:
      - es_data:/usr/share/elasticsearch/data
    networks:
      - app-network
    ports:
      - "9200:9200"

  # 3. Backend App Service
  backend:
    build: .
    restart: always # Tá»± khá»Ÿi Ä‘á»™ng láº¡i náº¿u MySQL chÆ°a sáºµn sÃ ng
    depends_on:
      - mysqldb
      - elasticsearch
    # ðŸ‘‡ DÃ²ng nÃ y quan trá»ng: Load toÃ n bá»™ biáº¿n tá»« .env vÃ o App
    env_file:
      - .env
    ports:
      - "8080:8080"
    networks:
      - app-network

volumes:
  db_data:
  es_data:

networks:
  app-network:
    driver: bridge