server:
  port: 8080
  servlet:
    context-path: /api

spring:
  datasource:
    url: ${DBMS_CONNECTION}
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: ${DBMS_USERNAME}
    password: ${DBMS_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
#    show-sql: true
#    format_sql: true
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

  elasticsearch:
    uris: ${ELASTICSEARCH_DBMS_CONNECTION}
#logging:
#  level:
#    org:
#      hibernate:
#        SQL: DEBUG
#        orm:
#          jdbc:
#            bind: TRACE


jwt:
  signerKey: ${JWT_SIGNER_KEY}
  valid-duration: ${JWT_VALID_DURATION} #in seconds
  refreshable-duration: ${REFRESHABLE_DURATION} #in seconds

cloudinary:
  cloud_name: ${CLOUDINARY_CLOUD_NAME}
  api_key: ${CLOUDINARY_API_KEY}
  api_secret: ${CLOUDINARY_API_SECRET}

openapi:
   service:
     title: "My API"
     version: "1.0.0"
     url: "http://localhost:8080/api"
