server:
  port: 8080
  servlet:
    context-path: /api


spring:
  datasource:
    url: ${DBMS_CONNECTION:jdbc:mysql://localhost:3306/store_db}
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: ${DBMS_USERNAME:root}
    password: ${DBMS_PASSWORD:root}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    format_sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  elasticsearch:
    uris: "http://localhost:9200"
#logging:
#  level:
#    org:
#      hibernate:
#        SQL: DEBUG
#        orm:
#          jdbc:
#            bind: TRACE


jwt:
  signerKey: "EIwK/6lmzSXatXSxFFgzVW+NxTt2a6kRGORp23UiIvjpVkbI6fkFLCeTvIEdRUwM"
  valid-duration: 3600 #in seconds
  refreshable-duration: 360000 #in seconds

cloudinary:
  cloud_name: "dyedoswp3"
  api_key: "189699368184473"
  api_secret: "_LI-sp9EDcO2NP_za3sqWm0sD6M"

